#!/bin/sh

#alias xrdb=xrdb -load ~/.config/X11/xresources
alias tmux='env TERM=screen-256color tmux'
alias wget=wget --hsts-file="$XDG_CACHE_HOME/wget-hsts"
alias tlmgr='/usr/share/texmf-dist/scripts/texlive/tlmgr.pl --usermode'
alias connect-air='bluetoothctl connect AC:90:85:CB:84:60&'
alias btblock='sudo rfkill block bluetooth'
alias btunblock='sudo rfkill unblock bluetooth'
alias phptags='ctags -R --fields=+aimlS --languages=php --output-format=e-ctags'
alias xbindkeys='xbindkeys -f "$XDG_CONFIG_HOME"/xbindkeys/config'
