#!/bin/bash

volume=$(pactl list sinks | grep "^[[:space:]]Volume" | head -n 1 | sed -e 's,.* \([0-9][0-9]*%\).*,\1,') || exit
sourdine=$(pactl list sinks | grep "^[[:space:]]Mute" | sed -e 's,.*: \([[:alpha:]]*\).*,\1,;s,yes,1,;s,no,0,')

if [ $sourdine -gt 0 ]; then
	echo 🔇
fi
echo 🔊 $volume
