#!/bin/bash

volume=$(amixer get Master | sed '/Mono:/p;d' | grep -o '[0-9]\+%') || exit
unmuted=$(amixer get Master | sed '/Mono:/p;d' | awk '{printf $6}' | sed 's:\[on\]:1:;s:\[off\]:0:')

[ $unmuted -eq 0 ] && echo 🔇&& exit
echo 🔊 $volume
