#!/bin/bash

#☔: Chance of rain/snow
#❄: Daily low
#🌞: Daily high

if [ $BLOCK_BUTTON -eq 1 ]; then
	st ~/.config/i3blocks/weatherhelp
fi

if [ $(date +%H) -lt 18 ]; then
	row=13
else
	row=23
fi

curl https://wttr.in/ > /tmp/weather
rainmm=$(cat /tmp/weather | sed "$(($row + 3))q;d" | grep -wo "[0-9]\+.[0-9]\+ mm" | sort -nr | sed '1q')
rain=$(cat /tmp/weather | sed "$(($row + 3))q;d" | grep -wo "[0-9]\+%" | sort -nr | sed '1q')
lowest=$(cat /tmp/weather | sed "$(($row))q;d" | grep -o "m-\?[0-9]\+" | cut -c 2- | sort -n | sed '1q')
highest=$(cat /tmp/weather | sed "$(($row))q;d" | grep -o "m-\?[0-9]\+" | cut -c 2- | sort -nr | sed '1q')

echo "☔$rain ❄$lowest° 🌞$highest°"

