let mapleader=" "

set nocompatible
set runtimepath+=$XDG_CONFIG_HOME/vim/
set runtimepath+=$XDG_CONFIG_HOME/vim/after
set runtimepath+=$XDG_CONFIG_HOME/vim/plugin
set runtimepath+=$XDG_CONFIG_HOME/vim/ftplugin
set packpath=$XDG_CONFIG_HOME/vim

" make make silent
set makeprg=make\ -s
" italic text
set t_ZH=[3m
set t_ZR=[23m

highlight StatusLine ctermbg=0 cterm=bold

" detect filetype
silent let s:filelist = systemlist("ls $XDG_CONFIG_HOME/vim/ftdetect/")
for s:filename in s:filelist
	let s:file = '$XDG_CONFIG_HOME/vim/ftdetect/' . s:filename
	execute 'source ' . s:file
endfor

highlight link Jump Function
match Jump '<++>'

if has('packages')
	" here packadd!
	"packadd! onedark.vim
	packadd! goyo.vim
endif

set background=dark
if filereadable(expand("~/.vimrc_background"))
	let base16colorspace=256
	source ~/.vimrc_background
endif

filetype plugin indent on
syntax on
