let mapleader=" "

set nocompatible
set runtimepath+=$XDG_CONFIG_HOME/vim/
set runtimepath+=$XDG_CONFIG_HOME/vim/after
set runtimepath+=$XDG_CONFIG_HOME/vim/plugin
set runtimepath+=$XDG_CONFIG_HOME/vim/ftplugin

call plug#begin($XDG_CONFIG_HOME . '/vim/plugged')
    Plug 'navarasu/onedark.nvim'
    Plug 'vim-airline/vim-airline'
    Plug 'vim-airline/vim-airline-themes'
    Plug 'tpope/vim-fugitive'
call plug#end()

" make make silent
set makeprg=make\ -s
" italic text
set t_ZH=[3m
set t_ZR=[23m

" detect filetype
silent let s:filelist = systemlist("ls $XDG_CONFIG_HOME/vim/ftdetect/")
for s:filename in s:filelist
	let s:file = '$XDG_CONFIG_HOME/vim/ftdetect/' . s:filename
	execute 'source ' . s:file
endfor

highlight link Jump Function
match Jump '<++>'

colorscheme onedark
